![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**
#10.5. Fayldan oʻqish va unga yozish. HDF5
**Bu vazifalarni bajargach, CSV, Excel va HDF5 formatlarida fayllarni oʻqish hamda saqlash, yaʼni data processing (ma’lumotlarga ishlov berish) koʻnikmasini oʻzlashtirasiz.**


#1-topshiriq


1.    Quyidagi link orqali maʼlumotlarni Pandas dataframeʼiga yuklab oling.
    
  *   https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv



2.   Yuklab olingan maʼlumotlarni `aqi.csv` fayliga saqlang.

3. Saqlab olingan `aqi.csv` faylining oxirgi 5 ta qatorini oʻqing.

Eslatma: fayl nomini `aqi.csv` deb saqlaganimizning sababi AQI – Air Quality Index, yaʼni havo sifati indeksi deganidir. Bizning maʼlumotlarimizda davlatlarning havo sifati haqidagi maʼlumotlar saqlangan!

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv"
#javobni shu yerda yozing.
aqi = pd.read_csv("https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv")
aqi.to_csv('aqi.csv')
aqi.tail()

             Date                   Country    Status  AQI Value
18116  2025-03-06  United States of America  Moderate         82
18117  2025-03-06                Uzbekistan      Good         17
18118  2025-03-06                   Vatican  Moderate         65
18119  2025-03-06                 Venezuela      Good         11
18120  2025-03-06                   Vietnam  Moderate         64

#2-topshiriq
1. Saqlab olingan `aqi.csv` faylidagi maʼlumotlarning faqat 2024-yilga tegishlisini excel faylga `aqi_2024.xlsx` koʻrinishida saqlab oling.
2. Saqlab olingan `aqi_2024.xlsx` faylidan Oʻzbekistonga tegishli maʼlumotni (qatorlarni) oʻqing.

In [ ]:
#javobni shu yerda yozing.
aqi_2024 = aqi[aqi.Date >= '2024-01-01'][aqi.Date <= '2025-01-01']
aqi_2024.to_excel('aqi_2024.xlsx')

/tmp/ipython-input-1969546241.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  aqi_2024 = aqi[aqi.Date >= '2024-01-01'][aqi.Date <= '2025-01-01']

In [ ]:
aqi_2024.loc[aqi_2024.Country == 'Uzbekistan']

             Date     Country     Status  AQI Value
13114  2024-06-06  Uzbekistan       Good         21
13247  2024-06-06  Uzbekistan       Good         21
13380  2024-06-13  Uzbekistan       Good         35
13511  2024-06-20  Uzbekistan       Good         10
13642  2024-06-27  Uzbekistan       Good         26
13772  2024-07-04  Uzbekistan       Good         19
13900  2024-07-11  Uzbekistan       Good         26
14029  2024-07-18  Uzbekistan       Good         42
14159  2024-07-25  Uzbekistan       Good         30
14288  2024-08-01  Uzbekistan       Good         45
14418  2024-08-08  Uzbekistan       Good         42
14548  2024-08-15  Uzbekistan       Good         26
14677  2024-08-22  Uzbekistan       Good         23
14805  2024-08-29  Uzbekistan   Moderate         56
14934  2024-09-05  Uzbekistan   Moderate         70
15061  2024-09-12  Uzbekistan       Good         45
15190  2024-09-19  Uzbekistan  Hazardous        500
15317  2024-09-26  Uzbekistan  Unhealthy        157
15436  2024-10-03  Uzbekistan       Good         34
15564  2024-10-10  Uzbekistan   Moderate         63
15686  2024-10-17  Uzbekistan  Unhealthy        195
15807  2024-10-24  Uzbekistan  Unhealthy        180
15927  2024-10-31  Uzbekistan  Unhealthy        153
16046  2024-11-07  Uzbekistan   Moderate         65
16165  2024-11-14  Uzbekistan  Unhealthy        151
16283  2024-11-21  Uzbekistan  Unhealthy        152
16405  2024-11-28  Uzbekistan       Good         38
16527  2024-12-05  Uzbekistan   Moderate         83
16649  2024-12-12  Uzbekistan   Moderate        100
16772  2024-12-19  Uzbekistan       Good         34
16893  2024-12-26  Uzbekistan   Moderate         98

#3-topshiriq
1. `aqi.csv` faylidagi maʼlumotlarni oʻrganib chiqsangiz, bu faylda 2022–2025-yillar oraligʻidagi havo sifati haqidagi maʼlumotlarni koʻrishingiz mumkin. Hozir sizga vazifa:
  * `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllariga `aqi.csv` faylidagi maʼlumotlarning mos davrlarini saqlang. Misol uchun, `aqi_2022` fayli 2022-yildagi havo sifati haqidagi maʼlumotlarni oʻzida saqlaydi.

In [ ]:
#javobni shu yerda yozing.
# 2022 -yil bo'yicha ma'lumotlar
aqi_2022 = aqi[aqi.Date <= '2023-01-01']
aqi_2022.to_csv('aqi_2022.csv')

In [ ]:
# 2023 -yil bo'yicha ma'lumotlar
aqi_2023 = aqi[aqi.Date >= '2023-01-01'][aqi.Date <= '2024-01-01']
aqi_2023.to_csv('aqi_2023.csv')

/tmp/ipython-input-3693131899.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  aqi_2023 = aqi[aqi.Date >= '2023-01-01'][aqi.Date <= '2024-01-01']

In [ ]:
# 2024 -yil bo'yicha ma'lumotlar
aqi_2024 = aqi[aqi.Date >= '2024-01-01'][aqi.Date <= '2025-01-01']
aqi_2024.to_csv('aqi_2024.csv')

/tmp/ipython-input-1738357104.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  aqi_2024 = aqi[aqi.Date >= '2024-01-01'][aqi.Date <= '2025-01-01']

In [ ]:
# 2025 -yil bo'yicha ma'lumotlar
aqi_2025 = aqi[aqi.Date >= '2025-01-01']
aqi_2025.to_csv('aqi_2025.csv')

#4-topshiriq
1. Saqlab olingan `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllarini HDF5 formatida saqlang. Fayl nomini `aqi.h5` deb nomlang. Kalit (key) sifatida fayllarning yillarini bering. Misol uchun, key=2025.

In [ ]:
#javobni shu yerda yozing.
aqi_h5 = pd.HDFStore('aqi.h5')
aqi_h5.put('2022', aqi_2022)
aqi_h5.put('2023', aqi_2023)
aqi_h5.put('2024', aqi_2024)
aqi_h5.put('2025', aqi_2025)

/usr/local/lib/python3.12/dist-packages/tables/path.py:146: NaturalNameWarning: object name is not a valid Python identifier: '2022'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.12/dist-packages/tables/path.py:146: NaturalNameWarning: object name is not a valid Python identifier: '2023'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.12/dist-packages/tables/path.py:146: NaturalNameWarning: object name is not a valid Python identifier: '2024'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.12/dist-packages/tables/path.py:146: NaturalNameWarning: object name is not a valid Python identifier: '2025'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

In [ ]:
aqi_h5.close()

#5-topshiriq
1. `aqi.h5` faylidan maʼlumotlarni oʻqing va 2025-yilga tegishli maʼlumotlarni yangi dataframeʼga saqlang.
2. `aqi.h5` faylida 2025-yilning qaysi oylari uchun maʼlumotlar bor? Shu oylar roʻyxatini ekranga chiqaring!

In [ ]:
#javobni shu yerda yozing.
aqi_h5 = pd.HDFStore('aqi.h5')
aqi_h5_25 = aqi_h5['2025']
aqi_h5.close()

In [ ]:
aqi_h5_25

,Date,Country,Status,AQI Value
16897,2025-01-02,Albania,Good,25
16898,2025-01-02,Algeria,Unhealthy for Sensitive Groups,137
16899,2025-01-02,Andorra,Good,11
16900,2025-01-02,Argentina,Good,25
16901,2025-01-02,Armenia,Moderate,69
...,...,...,...,...
18116,2025-03-06,United States of America,Moderate,82
18117,2025-03-06,Uzbekistan,Good,17
18118,2025-03-06,Vatican,Moderate,65
18119,2025-03-06,Venezuela,Good,11
18120,2025-03-06,Vietnam,Moderate,64