In [ ]:
import numpy as np
import pandas as pd

In [3]:
df_2015 = pd.read_csv(r"C:\Users\obidjon\Downloads\happens\2015.csv") 
df_2016 = pd.read_csv(r"C:\Users\obidjon\Downloads\happens\2016.csv")
df_2017 = pd.read_csv(r"C:\Users\obidjon\Downloads\happens\2017.csv")
df_2018 = pd.read_csv(r"C:\Users\obidjon\Downloads\happens\2018.csv")
df_2019 = pd.read_csv(r"C:\Users\obidjon\Downloads\happens\2019.csv")
df_2020 = pd.read_csv(r"C:\Users\obidjon\Downloads\happens\2020.csv")
df_2021 = pd.read_csv(r"C:\Users\obidjon\Downloads\happens\2021.csv")

# hamma DataFrame larni yuklab olamiz

In [4]:
df_2015.head(3)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204

In [5]:
df_2016.head(3)

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137

In [6]:
df_2017.head(3)

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715

In [7]:
df_2018.head(3)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408

In [8]:
df_2019.head(3)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341

In [9]:
df_2020.head(3)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267

In [10]:
df_2021.head(3)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839

In [11]:
df_drop_2015 = df_2015.drop(['Standard Error',
                              'Economy (GDP per Capita)',
                              'Family',
                              'Health (Life Expectancy)',
                              'Freedom',
                              'Trust (Government Corruption)',
                              'Generosity',
                              'Dystopia Residual'], axis=1)
# DataFramedagi bizga zarur bo'lmagan ustunlarni tashlab yuboramiz

In [12]:
df_irarxik_2015 =  pd.pivot_table(df_drop_2015, index = ['Region','Country'],
                                  values = ['Happiness Rank','Happiness Score']) 
df_irarxik_2015.head(3)
# irarxik indeksli ma'lumotlar to'plamiga o'tish 2015 yilga tegishli ma'lumotlar uchun

                                        Happiness Rank  Happiness Score
Region                     Country
Australia and New Zealand  Australia              10.0            7.284
                           New Zealand             9.0            7.286
Central and Eastern Europe Albania                95.0            4.959

In [13]:
df_drop_2016 = df_2016.drop(['Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'], axis=1)
# DataFramedagi bizga zarur bo'lmagan ustunlarni tashlab yuboramiz

In [14]:
df_irarxik_2016 =  pd.pivot_table(df_drop_2016, index = ['Region','Country'],
                                  values = ['Happiness Rank','Happiness Score']) 
df_irarxik_2016.head(3)
# irarxik indeksli ma'lumotlar to'plamiga o'tish 2016 yilga tegishli ma'lumotlar uchun

                                        Happiness Rank  Happiness Score
Region                     Country
Australia and New Zealand  Australia               9.0            7.313
                           New Zealand             8.0            7.334
Central and Eastern Europe Albania               109.0            4.655

In [15]:
df_drop_2017 = df_2017.drop(['Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],axis=1)
# DataFramedagi bizga zarur bo'lmagan ustunlarni tashlab yuboramiz

In [16]:
df_drop_2017.rename(columns={'Happiness.Rank':'Happiness Rank',
                             'Happiness.Score':'Happiness Score'}, inplace=True)
# Avvalo 2017 yildagi ustunlaridagi xatoni to'girladek

In [17]:
dfrc = df_2016[['Region','Country']] # 2016 yilgi iiki ustunni chaqirib oldek
dfc = df_2017[['Country']] # 2017 yilgi faqat mavjud Country ustunini chaqirib oldek
data = pd.merge(dfrc,dfc, how='right') # shu ikki dataset orasini bo'gladek
df_region = data['Region'] # va shu bo'glangan datasetdan Region ustunini oldek

In [18]:
df_irarxik_2017 =  pd.pivot_table(df_drop_2017, index = [df_region,'Country'],
                                  values = ['Happiness Rank','Happiness Score']) 
df_irarxik_2017.head(3)
# Avvalgi qismdagi Region ustunini shu datasetda mavjud bo'lmagan ustunlar ro'yxatiga qo'shdek
# irarxik indeksli ma'lumotlar to'plamiga o'tish 2017 yilga tegishli ma'lumotlar uchun

                                        Happiness Rank  Happiness Score
Region                     Country
Australia and New Zealand  Australia              10.0            7.284
                           New Zealand             8.0            7.314
Central and Eastern Europe Albania               109.0            4.644

In [19]:
df_drop_2018 = df_2018.drop(['GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],axis=1)
# 2018 yilda tegishli datasetdagi no zarur ustunlarni uchirdek

In [20]:
df_drop_2018.rename(columns={'Overall rank':'Happiness Rank', 'Country or region':'Country', 'Score':'Happiness Score'}, inplace=True)
# ustunlardagi xato nomlarni o'zimizga kerakli nomga o'zgartirdek

In [21]:
df_irarxik_2018 =  pd.pivot_table(df_drop_2018, index = [df_region,'Country'],
                                  values = ['Happiness Rank','Happiness Score']) 
df_irarxik_2018.head(3)
# Avvalgi qismdagi Region ustunini shu datasetda mavjud bo'lmagan ustunlar ro'yxatiga qo'shdek
# irarxik indeksli ma'lumotlar to'plamiga o'tish 2018 yilga tegishli ma'lumotlar uchun

                                        Happiness Rank  Happiness Score
Region                     Country
Australia and New Zealand  Australia              10.0            7.272
                           New Zealand             8.0            7.324
Central and Eastern Europe Belarus                73.0            5.483

In [22]:
df_drop_2019 = df_2019.drop(['GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],axis=1)

In [23]:
df_drop_2019.rename(columns={'Overall rank':'Happiness Rank', 'Country or region':'Country', 'Score':'Happiness Score'}, inplace=True)
# ustunlardagi xato nomlarni o'zimizga kerakli nomga o'zgartirdek

In [24]:
df_irarxik_2019 =  pd.pivot_table(df_drop_2019, index = [df_region,'Country'],
                                  values = ['Happiness Rank','Happiness Score']) 
df_irarxik_2019.head(3)
# Avvalgi qismdagi Region ustunini shu datasetda mavjud bo'lmagan ustunlar ro'yxatiga qo'shdek
# irarxik indeksli ma'lumotlar to'plamiga o'tish 2019 yilga tegishli ma'lumotlar uchun

                                        Happiness Rank  Happiness Score
Region                     Country
Australia and New Zealand  Austria                10.0            7.246
                           New Zealand             8.0            7.307
Central and Eastern Europe Argentina              47.0            6.086

In [25]:
df_drop_2020 = df_2020.drop(['Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],axis=1)

In [26]:
df_drop_2020.rename(columns={'Country name':'Country','Regional indicator':'Region','Ladder score':'Happiness Score'}, inplace=True)
# ustunlardagi xato nomlarni o'zimizga kerakli nomga o'zgartirdek

In [27]:
df_irarxik_2020 =  pd.pivot_table(df_drop_2020, index = ['Region','Country'],
                                  values = ['Happiness Score']) 
df_irarxik_2020.head(3)
# irarxik indeksli ma'lumotlar to'plamiga o'tish 2020 yilga tegishli ma'lumotlar uchun

                                                   Happiness Score
Region                     Country
Central and Eastern Europe Albania                          4.8827
                           Bosnia and Herzegovina           5.6741
                           Bulgaria                         5.1015

In [28]:
df_drop_2021 = df_2021.drop(['Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],axis=1)

In [29]:
df_drop_2021.rename(columns={'Country name':'Country','Regional indicator':'Region','Ladder score':'Happiness Score'},inplace=True)
# ustunlardagi xato nomlarni o'zimizga kerakli nomga o'zgartirdek

In [30]:
df_irarxik_2021 =  pd.pivot_table(df_drop_2021, index = ['Region','Country'],
                                  values = ['Happiness Score']) 
df_irarxik_2021.head(3)
# irarxik indeksli ma'lumotlar to'plamiga o'tish 2021 yilga tegishli ma'lumotlar uchun

                                                   Happiness Score
Region                     Country
Central and Eastern Europe Albania                           5.117
                           Bosnia and Herzegovina            5.813
                           Bulgaria                          5.266

In [90]:
df_drop_2019[df_drop_2019['Country']=='Albania']

     Happiness Rank  Country  Happiness Score                           Region
106             107  Albania            4.719  Middle East and Northern Africa

In [78]:
data_2015 = pd.DataFrame(df_irarxik_2015.values, index = df_irarxik_2015.index, columns= [['2015','2015'],['Happiness Rank','Happiness Score']])
data_2016 = pd.DataFrame(df_irarxik_2016.values, index =df_irarxik_2016.index, columns= [['2016','2016'],['Happiness Rank','Happiness Score']])
data_2017 = pd.DataFrame(df_irarxik_2017.values, index = df_irarxik_2017.index, columns= [['2017','2017'],['Happiness Rank','Happiness Score']])
data_2018 = pd.DataFrame(df_irarxik_2018.values, index =df_irarxik_2018.index, columns= [['2018','2018'],['Happiness Rank','Happiness Score']])
data_2019 = pd.DataFrame(df_irarxik_2019.values, index =df_irarxik_2019.index, columns= [['2019','2019'],['Happiness Rank','Happiness Score']])
data_2020 = pd.DataFrame(df_irarxik_2020.values, index = df_irarxik_2020.index, columns= [['2020'],['Happiness Score']])
data_2021 = pd.DataFrame(df_irarxik_2021.values, index =df_irarxik_2021.index, columns= [['2021'],['Happiness Score']])

In [79]:
df_concat = pd.concat([data_2015,data_2016,data_2017,data_2018,data_2019,data_2020,data_2021],axis=1)

In [133]:
df_concat.dropna(inplace=True)
df_concat

                                                 2015                  \
                                       Happiness Rank Happiness Score
Region                     Country
Central and Eastern Europe Kosovo                69.0           5.589
Sub-Saharan Africa         Ethiopia             122.0           4.512
                           Guinea               150.0           3.656
                           Madagascar           147.0           3.681
                           Malawi               131.0           4.292
                           Mali                 138.0           3.995
                           Tanzania             146.0           3.781
                           Uganda               141.0           3.931
Western Europe             Belgium               19.0           6.937
                           Denmark                3.0           7.527
                           Finland                6.0           7.406
                           Germany               26.0           6.750
                           Iceland                2.0           7.561
                           Netherlands            7.0           7.378
                           Norway                 4.0           7.522
                           Switzerland            1.0           7.587

                                                 2016                  \
                                       Happiness Rank Happiness Score
Region                     Country
Central and Eastern Europe Kosovo                77.0           5.401
Sub-Saharan Africa         Ethiopia             115.0           4.508
                           Guinea               151.0           3.607
                           Madagascar           148.0           3.695
                           Malawi               132.0           4.156
                           Mali                 135.0           4.073
                           Tanzania             149.0           3.666
                           Uganda               145.0           3.739
Western Europe             Belgium               18.0           6.929
                           Denmark                1.0           7.526
                           Finland                5.0           7.413
                           Germany               16.0           6.994
                           Iceland                3.0           7.501
                           Netherlands            7.0           7.339
                           Norway                 4.0           7.498
                           Switzerland            2.0           7.509

                                                 2017                  \
                                       Happiness Rank Happiness Score
Region                     Country
Central and Eastern Europe Kosovo                78.0           5.279
Sub-Saharan Africa         Ethiopia             119.0           4.460
                           Guinea               149.0           3.507
                           Madagascar           144.0           3.644
                           Malawi               136.0           3.970
                           Mali                 127.0           4.190
                           Tanzania             153.0           3.349
                           Uganda               133.0           4.081
Western Europe             Belgium               17.0           6.891
                           Denmark                2.0           7.522
                           Finland                5.0           7.469
                           Germany               16.0           6.951
                           Iceland                3.0           7.504
                           Netherlands            6.0           7.377
                           Norway                 1.0           7.537
                           Switzerland            4.0           7.494

                                                 2018                  \
                                       Happiness Rank Happiness Score
Region                     Country
Central and Eastern Europe Kosovo                66.0           5.662
Sub-Saharan Africa         Ethiopia             127.0           4.350
                           Guinea               140.0           3.964
                           Madagascar           143.0           3.774
                           Malawi               147.0           3.587
                           Mali                 118.0           4.447
                           Tanzania             153.0           3.303
                           Uganda               135.0           4.161
Western Europe             Belgium               16.0           6.927
                           Denmark                3.0           7.555
                           Finland                1.0           7.632
                           Germany               15.0           6.965
                           Iceland                4.0           7.495
                           Netherlands            6.0           7.441
                           Norway                 2.0           7.594
                           Switzerland            5.0           7.487

                                                 2019                  \
                                       Happiness Rank Happiness Score
Region                     Country
Central and Eastern Europe Kosovo                46.0           6.100
Sub-Saharan Africa         Ethiopia             134.0           4.286
                           Guinea               118.0           4.534
                           Madagascar           143.0           3.933
                           Malawi               150.0           3.410
                           Mali                 128.0           4.390
                           Tanzania             153.0           3.231
                           Uganda               136.0           4.189
Western Europe             Belgium               18.0           6.923
                           Denmark                2.0           7.600
                           Finland                1.0           7.769
                           Germany               17.0           6.985
                           Iceland                4.0           7.494
                           Netherlands            5.0           7.488
                           Norway                 3.0           7.554
                           Switzerland            6.0           7.480

                                                  2020            2021
                                       Happiness Score Happiness Score
Region                     Country
Central and Eastern Europe Kosovo               6.3252           6.372
Sub-Saharan Africa         Ethiopia             4.1862           4.275
                           Guinea               4.9493           4.984
                           Madagascar           4.1656           4.208
                           Malawi               3.5380           3.600
                           Mali                 4.7293           4.723
                           Tanzania             3.4762           3.623
                           Uganda               4.4320           4.636
Western Europe             Belgium              6.8635           6.834
                           Denmark              7.6456           7.620
                           Finland              7.8087           7.842
                           Germany              7.0758           7.155
                           Iceland              7.5045           7.554
                           Netherlands          7.4489           7.464
                           Norway               7.4880           7.392
                           Switzerland          7.5599           7.571

In [116]:
df_d2015 = df_drop_2015.drop(['Region'],axis=1)
df_d2016 = df_drop_2016.drop(['Region'],axis=1)
df_d2018 = df_drop_2018.drop(['Region'],axis=1)
df_d2019 = df_drop_2019.drop(['Region'],axis=1)
df_d2020 = df_drop_2020.drop(['Region'],axis=1)
df_d2021 = df_drop_2021.drop(['Region'],axis=1)

In [119]:
data_d2015 = pd.DataFrame(df_d2015.values, index = df_d2015.index, columns= [['2015','2015','2015'],['Country','Happiness Rank','Happiness Score']])
data_d2016 = pd.DataFrame(df_d2016.values, index =df_d2016.index, columns= [['2016','2016','2016'],['Country','Happiness Rank','Happiness Score']])
data_d2017 = pd.DataFrame(df_drop_2017.values, index = df_drop_2017.index, columns= [['2017','2017','2017'],['Country','Happiness Rank','Happiness Score']])
data_d2018 = pd.DataFrame(df_d2018.values, index =df_drop_2018.index, columns= [['2018','2018','2018'],['Country','Happiness Rank','Happiness Score']])
data_d2019 = pd.DataFrame(df_d2019.values, index =df_drop_2019.index, columns= [['2019','2019','2019'],['Country','Happiness Rank','Happiness Score']])
data_d2020 = pd.DataFrame(df_d2020.values, index = df_d2020.index, columns= [['2020','2020'],['Country','Happiness Score']])
data_d2021 = pd.DataFrame(df_d2021.values, index =df_d2021.index, columns= [['2021','2021'],['Country','Happiness Score']])

In [120]:
df_concat_2 = pd.concat([data_d2015,data_d2016,data_d2017,data_d2018,data_d2019,data_d2020,data_d2021],axis=1)

In [134]:
df_concat_2.dropna(inplace=True)
df_concat_2

                         2015                                         2016  \
                      Country Happiness Rank Happiness Score       Country
0                 Switzerland              1           7.587       Denmark
1                     Iceland              2           7.561   Switzerland
2                     Denmark              3           7.527       Iceland
3                      Norway              4           7.522        Norway
4                      Canada              5           7.427       Finland
..                        ...            ...             ...           ...
144                  Cambodia            145           3.819  Burkina Faso
145                  Tanzania            146           3.781        Uganda
146                Madagascar            147           3.681         Yemen
147  Central African Republic            148           3.678    Madagascar
148                      Chad            149           3.667      Tanzania

                                           2017                 \
    Happiness Rank Happiness Score      Country Happiness Rank
0                1           7.526       Norway              1
1                2           7.509      Denmark              2
2                3           7.501      Iceland              3
3                4           7.498  Switzerland              4
4                5           7.413      Finland              5
..             ...             ...          ...            ...
144            145           3.739        Haiti            145
145            145           3.739        Yemen            146
146            147           3.724  South Sudan            147
147            148           3.695      Liberia            148
148            149           3.666       Guinea            149

                       2018                                   2019  \
    Happiness Score Country Happiness Rank Happiness Score Country
0             7.537       1        Finland           7.632       1
1             7.522       2         Norway           7.594       2
2             7.504       3        Denmark           7.555       3
3             7.494       4        Iceland           7.495       4
4             7.469       5    Switzerland           7.487       5
..              ...     ...            ...             ...     ...
144           3.603     145    Afghanistan           3.632     145
145           3.593     146       Botswana            3.59     146
146           3.591     147         Malawi           3.587     147
147           3.533     148          Haiti           3.582     148
148           3.507     149        Liberia           3.495     149

                                                        2020                  \
    Happiness Rank Happiness Score                   Country Happiness Score
0          Finland           7.769                   Finland          7.8087
1          Denmark             7.6                   Denmark          7.6456
2           Norway           7.554               Switzerland          7.5599
3          Iceland           7.494                   Iceland          7.5045
4      Netherlands           7.488                    Norway           7.488
..             ...             ...                       ...             ...
144        Burundi           3.775                    Malawi           3.538
145       Zimbabwe           3.663                     Yemen          3.5274
146          Haiti           3.597                  Botswana          3.4789
147       Botswana           3.488                  Tanzania          3.4762
148          Syria           3.462  Central African Republic          3.4759

            2021
         Country Happiness Score
0        Finland           7.842
1        Denmark            7.62
2    Switzerland           7.571
3        Iceland           7.554
4    Netherlands           7.464
..           ...             ...
144      Lesotho           3.512
145     Botswana           3.467
146       Rwanda           3.415
147     Zimbabwe           3.145
148  Afghanistan           2.523

[149 rows x 19 columns]